import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:generalized_dpp/pages/widget_tree.dart';

class ProductDetailPage extends StatelessWidget {
  final Map<dynamic, dynamic> product;
  final db = FirebaseFirestore.instance.collection('alumil_dummy');
  final documentID;

  ProductDetailPage({required this.product, required this.documentID});

  @override
  Widget build(BuildContext context) {
    final keys = product.keys.toList();

    return Scaffold(
      appBar: AppBar(title: Text(product['Product Name'] ?? 'Details')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            Text(
              'Here will be presented a small summary of the selected product. This summary is going to be generated by LLM model agent based on the fields that are presented as most important by the potential client.',
            ),

            Spacer(flex: 1),

            Table(
              border: TableBorder.all(),
              columnWidths: {0: FlexColumnWidth(2), 1: FlexColumnWidth(3)},
              children: [
                TableRow(
                  decoration: BoxDecoration(color: Colors.grey[300]),
                  children: [
                    Padding(
                      padding: EdgeInsets.all(8),
                      child: Text(
                        'Field',
                        style: TextStyle(fontWeight: FontWeight.bold),
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.all(8),
                      child: Text(
                        'Value',
                        style: TextStyle(fontWeight: FontWeight.bold),
                      ),
                    ),
                  ],
                ),
                ...keys.map((key) {
                  return TableRow(
                    children: [
                      Padding(
                        padding: EdgeInsets.all(8),
                        child: Text(key.toString()),
                      ),
                      Padding(
                        padding: EdgeInsets.all(8),
                        child: Text(product[key].toString()),
                      ),
                    ],
                  );
                }).toList(),
              ],
            ),

            Spacer(flex: 2),

            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                TextButton(
                  style: TextButton.styleFrom(
                    backgroundColor: Theme.of(
                      context,
                    ).colorScheme.primaryContainer,
                  ),
                  onPressed: () {},
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text('Edit Information'),
                  ),
                ),
                TextButton(
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text('Delete Product'),
                  ),
                  style: TextButton.styleFrom(
                    backgroundColor: Theme.of(
                      context,
                    ).colorScheme.primaryContainer,
                  ),
                  onPressed: () {
                    showCupertinoDialog(
                      context: context,
                      builder: (BuildContext context) {
                        return CupertinoAlertDialog(
                          title: Text('Are you sure?'),
                          content: const Text(
                            'This product is going to be permanently delete. Do you want to proceed?',
                          ),
                          actions: [
                            CupertinoDialogAction(
                              child: Text("Not yet"),
                              onPressed: () => Navigator.of(context).pop(),
                            ),
                            CupertinoDialogAction(
                              child: Text('Yes'),
                              onPressed: () => {
                                db
                                    .doc(documentID)
                                    .delete()
                                    .then((value) => print('Product delete'))
                                    .catchError(
                                      (e) => print("Error because: $e"),
                                    ),

                                Navigator.pushReplacement(
                                  context,
                                  CupertinoPageRoute(
                                    builder: (context) => WidgetTree(),
                                  ),
                                ),
                              },
                            ),
                          ],
                        );
                      },
                    );
                  },
                ),
              ],
            ),
            Spacer(flex: 1),
          ],
        ),
      ),
    );
  }
}
