import 'dart:ffi';

import 'package:flutter/material.dart';

class ProductDetailPage extends StatelessWidget {
  final Map<dynamic, dynamic> product;

  ProductDetailPage({required this.product});

  @override
  Widget build(BuildContext context) {
    final keys = product.keys.toList();

    return Scaffold(
      appBar: AppBar(title: Text(product['Product Name'] ?? 'Details')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [

            Text('Here will be presented a small summary of the selected product. This summary is going to be generated by LLM model agent based on the fields that are presented as most important by the potential client.'),


            Spacer(flex: 1,),
            
            Table(
              border: TableBorder.all(),
              columnWidths: {
                0: FlexColumnWidth(2),
                1: FlexColumnWidth(3),
              },
              children: [
                TableRow(
                  decoration: BoxDecoration(color: Colors.grey[300]),
                  children: [
                    Padding(
                      padding: EdgeInsets.all(8),
                      child: Text('Field', style: TextStyle(fontWeight: FontWeight.bold)),
                    ),
                    Padding(
                      padding: EdgeInsets.all(8),
                      child: Text('Value', style: TextStyle(fontWeight: FontWeight.bold)),
                    ),
                  ],
                ),
                ...keys.map((key) {
                  return TableRow(children: [
                    Padding(padding: EdgeInsets.all(8), child: Text(key.toString())),
                    Padding(padding: EdgeInsets.all(8), child: Text(product[key].toString())),
                  ]);
                }).toList(),
              ],
            ),

            Spacer(flex: 2,),

            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                TextButton(
                  style: TextButton.styleFrom(
                    backgroundColor: Theme.of(context).colorScheme.primaryContainer
                  ),
                  onPressed: () {
                    
                  },
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text('Edit Information'),
                  ),
                ),
                TextButton(
                  style: TextButton.styleFrom(backgroundColor: Theme.of(context).colorScheme.primaryContainer),
                  onPressed: () {
                    
                  },
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text('Delete Product'),
                  ),
                )
              ],
            ),

            Spacer(flex: 1,),
          ],
        ),
      ),
    );
  }
}
